### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by jbfavre** [vulogov/zlm-cython#1]
Hello Vladimir.
I'm trying to get zlm_python.c compiled with Zabbix 2.4.6, but got an error:

```
Building pyzabbix environment
Will compile against Zabbix from /home/dev/Debian/zabbix
Building python.cfg  ok
Building python.so
+ make -e all
gcc -g -fPIC -c -I/home/dev/Debian/zabbix/include -I/usr/include/libxml2 -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -o zlm_python.o zlm_python.c
In file included from zlm_python.c:6:0:
/home/dev/Debian/zabbix/include/sysinc.h:23:20: fatal error: config.h: No such file or directory
compilation terminated.
Makefile:9: recipe for target 'zlm_python.o' failed
make: *** [zlm_python.o] Error 1
+ set +x
```

Also tried with Zabbix 2.2 & 2.0 with same result.

OS: Debian sid
Command: LANG=C ./BUILD.sh
Current result: error
Expected result: compilation completes without error

Do you need more informations ?

**Comment by vulogov** [comment]
Did you run configure script for Zabbix ?

**Comment by jbfavre** [comment]
No, though I could use raw zabbix sources :-/
Works now, thanks :)

**Comment by vulogov** [comment]
Well, this is my problem too. I will modify BUILD.sh script that it will run configure for you.

**Comment by jbfavre** [comment]
Thanks :)
